spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: first-rest
          uri: http://localhost:9999  
          predicates:
            - Path=/loan/api/v1.0/**  

        - id: second-rest
          uri: http://localhost:8888  
          predicates:
            - Path=/loan/api/v2.0/** 
          
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/  
  
server:
  port: 8090  # Gateway runs on port 8090
