spring:
  application:
    name: servcie-from-hello
  cloud:
    gateway:
      routes:
        - id: first-rest
          uri: http://localhost:9999  
          predicates:
            - Path=/loan/api/v1.0/**  

          
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/  
  
server:
  port: 8094 
